### ISSUE TITLE
share inferred GRNs?

### ISSUE THREAD

**Issue by timedreamer** [OceaneCsn/integrative_GRN_N_induction#1]
Dear Océane,

I'm a postdoc from Coruzzi lab. It's nice to see out dataset get used by others for network inference.

Is it possible to share the `grn_RF` and `grn_lasso` inferred from the `weightedLASSO_weighteRF_tutorial.Rmd`. These are two optimized GRNs, right? I was trying to run the Rmd locally but had some issues.

I'm curious about the GRNs, compared with the one generated by Coruzzi lab.

Thanks in advance,
Ji

**Comment by timedreamer** [comment]
Sorry, maybe the *optimized GRNs* were from `Gene_specific_optimisation_of_TFBM_integration.Rmd`? 
I had the same error as running the `weightedLASSO_weighteRF_tutorial.Rmd`.

It would be great if you could share the best-optimized GRNs.

Thanks.
Ji

**Comment by OceaneCsn** [comment]
Hi Ji,
Thank you for your interest!
I have uploaded the final GRNs optimized with our approach, in the `inferred_GRN` folder.

The rdata file contains a list of two elements:
- `"importances"` : a list of two matrices, that are the fully connected n_TFs*n_genes importance matrices for weightedLASSO and weightedRF (averaged accross 10 replicates)
- `"grns"` : a list of 6 dataframes, that are the inferred edges from the importances of weightedLASSO and weightedRF and for three network densities (0.005,0.01,0.05).

The code to save these results can be found at the end of `Gene_specific_optimisation_of_TFBM_integration.Rmd`

Let me know if you need anything else, or if you want to discuss the comparison of our inferred networks.
Cheers,
Océane

**Comment by timedreamer** [comment]
Awesome!! Thanks for the super quick response. I can load without a problem.
Your paper is very interesting to us. Good luck with the paper!
Thanks again for sharing the data!

Ji
